### ISSUE TITLE
minette.iniのchannel_access_tokenの記載について

### ISSUE THREAD

**Issue by zakit1021** [uezo/linebot-project-template#1]
テンプレートのご提供ありがとうございます。大変参考になりました。

最終的にテンプレートでLINEボットの動作まで確認できましたが、気になることがございましたので、ご確認いただけますと幸いです。

# 質問

LINE Developers Consoleで確認した接続情報を`minette.ini`に設定した際に、LINEサーバーとの接続時にエラーが発生しました。とりあえず、接続情報を`minette.ini`ではなくハードコーディングすることで解消しました。

channel_access_tokenに`=`が含まれていることが原因と推測されますが、対処策（`=`が含まれる場合の`minette.ini`への記載方法など）がございましたら教えていただけないでしょうか。

⚠以下機密性の高い情報は一部書き換えています。

# 状況

## `minette.ini`の設定内容（抜粋）

- `channel_secret`と`channel_access_token`の文字数は実際とは異なります
- `channel_access_token`の途中に`/`が含まれ`=`で終わっていました

```ini
[line_bot_api]
channel_secret = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
channel_access_token = xxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/99/xxxxxx=
```

## エラーログ

本リポジトリのクローン後 LINE Developersで取得したChannel SecretとChannel Access Tokenを設定し、 ​`run.py`を実行したところ、以下のエラーメッセージが表示されました。

```
2021-06-17 17:02:43,180 - minette - ERROR - Request signiture is invalid: <InvalidSignatureError [Invalid signature. signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]>
Traceback (most recent call last):
 ​File "/home/xxxxxxxxxxxxx/.pyenv/versions/3.6.9/lib/python3.6/site-packages/minette/adapter/lineadapter.py", line 99, in handle_http_request
   ​request_headers.get("X-Line-Signature", ""))
 ​File "/home/xxxxxxxxxxxxx/.pyenv/versions/3.6.9/lib/python3.6/site-packages/linebot/webhook.py", line 143, in parse
   ​'Invalid signature. signature=' + signature)
linebot.exceptions.InvalidSignatureError: <InvalidSignatureError [Invalid signature. signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]>
```

# 暫定対応

エラーログからX-Line-Signatureの付近でエラーが出ていましたが、ngrokで確認したところLINEサーバからX-Line-Signatureは渡されていました。

Channel Access Tokenに`=`が含まれていることが原因ではないかと考え、次のように接続情報をハードコーディングしたところ、エラーは解消されました。

## `run.py`を書き換え

```python
padpter = LineAdapter(
   ​config_file="./minette.ini",
   ​dialog_router=MyDialogRouter,
   ​tagger=JanomeTagger,
   ​channel_secret="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   ​channel_access_token="xxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/99/xxxxxx=",
)
```

**Comment by uezo** [comment]
@zakit1021 値に`=`が入ることにより取得できなくなるということは手元の環境では再現しませんので、ひょっとするとファイルの読み込みに失敗しているのかもしれません。
ためしに`padapter.bot.config["line_bot_api"]["channel_secret"]`（`=`が含まれていない）あたりブレークポイントを設けて状態を見ていただくか、print してみてください。
もし上記も値がセットされていない（キーエラーとなり取得に失敗する）ようであれば、`config_file`の記述を相対ではなく絶対パスにしていただくことで読み取れるようになると思われます。

P.S.
もし違ったら恐縮ですが、6/10のLINE Developer Communityのセッションを聴講いただいている方でしたら、そこで扱ったテンプレートはこちらになります。紛らわしくてすみません。。

https://github.com/uezo/linebot-template

**Comment by zakit1021** [comment]
@uezo ご回答いただきありがとうございます。
おかげで解決いたしました。

助言頂いた内容から設定ファイルの記載自体が問題と思われましたので確認したところ、私の設定ファイルの記述に問題がありました（設定ファイルのコメントの位置が不適切でした。。。）

お手数おかけしました。。

`config_file`の記述はフルパス相対パスどちらでも動作することを確認しております。


また、最新のテンプレートもご紹介いただきありがとうございます。
ご推察のように6/10のLINE Developer Communityのセッションを聴講しておりましたが、コンパスの資料の確認が不十分でした。

https://linedevelopercommunity.connpass.com/event/212287/

参考にさせていただきます。


P.S.

YoutubeのLiveコメントでは、次のページのリンクが記載されていたようです。
https://github.com/uezo/linebot-project-template

**Comment by uezo** [comment]
@zakit1021 解決したとのこと、よかったです！Youtubeコメント欄の誤りご指摘、ありがとうございます。大変失礼いたしました、、
